name: presensi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 4.0.4
  cloud_firestore: any
  firebase_auth: any
  firebase_storage: any
  firebase_core: ^2.24.2
  location: 5.0.3
  geocoding: 2.2.0
  permission_handler: 10.4.5
  google_maps_flutter: 2.5.3
  http: 0.13.4
  flutter_osm_plugin: 0.60.4

  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_map: ^3.0.0
  latlng: ^2.0.7
  geolocator: ^11.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true
